{{- if and .Values.data.persistence.enabled (not .Values.data.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.persistenceClaimName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.data.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.data.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.data.persistence.size }}
  {{- if .Values.data.persistence.storageClass }}
  storageClassName: {{ .Values.data.persistence.storageClass }}
  {{- end }}
{{- end }}
