{{- if and (include "vaultwarden.adminEnabled" .) (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.adminSecretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.existingSecretTokenKey }}: {{ include "vaultwarden.adminToken" . | b64enc | quote }}
{{- end }}
{{- if and (include "vaultwarden.smtpPasswordEnabled" .) (not .Values.smtp.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.smtpSecretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.smtp.existingSecretPasswordKey }}: {{ include "vaultwarden.smtpPassword" . | b64enc | quote }}
{{- end }}
