{{- if and .Values.persistence.conf.enabled (not .Values.persistence.conf.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.confClaimName" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.conf.accessModes | nindent 4 }}
  {{- with .Values.persistence.conf.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.conf.size }}
{{- end }}
---
{{- if and .Values.persistence.work.enabled (not .Values.persistence.work.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.workClaimName" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.work.accessModes | nindent 4 }}
  {{- with .Values.persistence.work.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.work.size }}
{{- end }}
