{{- if and (include "adguard-home.hasConfig" .) (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adguard-home.fullname" . }}-config
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
stringData:
  AdGuardHome.yaml: |
    {{- toYaml .Values.config.adGuardHome | nindent 4 }}
{{- end }}
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adguard-home.fullname" . }}-backup
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
stringData:
  access-key: {{ .Values.backup.s3.accessKey | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
