{{- if and .Values.sync.enabled (not .Values.sync.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adguard-home.fullname" . }}-sync
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
    app.kubernetes.io/component: sync
stringData:
  ORIGIN_URL: {{ .Values.sync.origin.url | quote }}
  ORIGIN_USERNAME: {{ .Values.sync.origin.username | quote }}
  ORIGIN_PASSWORD: {{ .Values.sync.origin.password | quote }}
  {{- range $i, $replica := .Values.sync.replicas }}
  REPLICA{{ add1 $i }}_URL: {{ $replica.url | quote }}
  REPLICA{{ add1 $i }}_USERNAME: {{ $replica.username | quote }}
  REPLICA{{ add1 $i }}_PASSWORD: {{ $replica.password | quote }}
  {{- end }}
{{- end }}
