mode: production

hostname:
  hostname: https://sso.example.com
  admin: https://admin-sso.example.com

database:
  vendor: postgres
  host: postgresql-rw.default.svc
  port: 5432
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

replicaCount: 3

cache:
  enabled: true
  stack: jdbc-ping

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: sso.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sso.example.com
      secretName: keycloak-tls

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

pdb:
  enabled: true
