mode: production

hostname:
  hostname: https://sso.example.com
  admin: https://admin-sso.example.com

database:
  vendor: postgres
  host: postgresql-rw.default.svc
  port: 5432
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

resourcesPreset: medium
priorityClassName: platform-critical

replicaCount: 2

pdb:
  enabled: true
