mode: production

hostname:
  hostname: https://sso.example.com

database:
  vendor: postgres
  host: postgresql-rw.default.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

realmImport:
  enabled: true
  existingConfigMap: keycloak-realms
