{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-username: {{ .Values.auth.rootUser | b64enc | quote }}
  {{- if .Values.auth.rootPassword }}
  mongodb-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and (include "mongodb.needsKeyFile" .) (not .Values.auth.existingKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.keySecretName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.replicaSetKey }}
  replica-set-key: {{ .Values.auth.replicaSetKey | b64enc | quote }}
  {{- else }}
  replica-set-key: {{ randAlphaNum 756 | b64enc | quote }}
  {{- end }}
{{- end }}
