apiVersion: v2
name: authelia
description: Authelia authentication and authorization server with SSO, MFA, and OpenID Connect
type: application
version: 0.1.0
appVersion: "4.39.16"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - authelia
  - authentication
  - authorization
  - sso
  - mfa
  - oidc
  - forward-auth
home: https://helmforge.dev/docs/charts/authelia
sources:
  - https://github.com/helmforgedev/charts/tree/main/charts/authelia
  - https://github.com/authelia/authelia
icon: https://www.authelia.com/images/branding/logo-cropped.png
dependencies:
  - name: postgresql
    version: 1.5.2
    repository: oci://ghcr.io/helmforgedev/helm
    condition: postgresql.enabled
  - name: mysql
    version: 1.4.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
  - name: redis
    version: 1.2.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: redis.enabled
