workload:
  enabled: true
  type: DaemonSet
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

imageTagFormat: simple
image:
  repository: fluent/fluentd
  tag: "v1.17"

containers:
  - name: fluentd
    ports:
      - containerPort: 24224

tolerations:
  - operator: Exists

service:
  port: 24224
  targetPort: 24224
