{{- if and (eq (include "uptime-kuma.dbType" .) "mariadb") (not .Values.mysql.enabled) (not .Values.database.external.existingSecret) .Values.database.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "uptime-kuma.fullname" .) }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.external.password | quote }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) (or .Values.backup.s3.accessKey .Values.backup.s3.secretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.backupSecretName" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "uptime-kuma.backupSecretAccessKeyKey" . }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ include "uptime-kuma.backupSecretSecretKeyKey" . }}: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
