apiVersion: v2
name: minecraft
type: application
version: 0.1.0
appVersion: "latest"
description: A Helm chart for deploying Minecraft Java Edition servers on Kubernetes
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - minecraft
  - game-server
  - java
  - paper
  - forge
  - fabric
  - geyser
  - bedrock
home: https://www.minecraft.net
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/r/itzg/minecraft-server
icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon-32x32.png
