# CI: Metrics and ServiceMonitor enabled
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      release: prometheus

php:
  ini: |
    upload_max_filesize = 64M
    post_max_size = 64M
