{{- if and .Values.usersDatabase.enabled (not .Values.usersDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authelia.fullname" . }}-users
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
stringData:
  users_database.yml: |
    users:
      {{- if .Values.usersDatabase.users }}
      {{- toYaml .Values.usersDatabase.users | nindent 6 }}
      {{- else }}
      {}
      {{- end }}
{{- end }}
