name: Bug Report
description: Report a bug in a Helm chart
labels: ["bug"]
body:
  - type: dropdown
    id: chart
    attributes:
      label: Chart
      description: Which chart is affected?
      options:
        - generic
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Chart Version
      placeholder: "1.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: values
    attributes:
      label: Values (relevant snippet)
      render: yaml

  - type: textarea
    id: error
    attributes:
      label: Error output
      render: shell
