apiVersion: v2
name: pihole
type: application
version: 1.0.0
appVersion: "2025.03.0"
description: A Helm chart for deploying Pi-hole DNS sinkhole on Kubernetes
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - pihole
  - dns
  - ad-blocker
  - network
  - dnsmasq
  - unbound
home: https://pi-hole.net
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/r/pihole/pihole
icon: https://pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
