apiVersion: v2
name: wordpress
type: application
version: 1.0.0
appVersion: "6.9.4"
description: A Helm chart for deploying WordPress on Kubernetes with MySQL support and S3 backup
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - wordpress
  - cms
  - blog
  - php
  - mysql
home: https://wordpress.org
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/wordpress
icon: https://s.w.org/style/images/about/WordPress-logotype-simplified.png
dependencies:
  - name: mysql
    version: 1.4.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
