apiVersion: v2
name: keycloak
description: Keycloak for Kubernetes with explicit dev and production modes
type: application
version: 2.0.0
appVersion: "26.5.5"
kubeVersion: ">=1.26.0-0"
keywords:
  - keycloak
  - identity
  - oidc
  - sso
maintainers:
  - name: helmforgedev
  - name: mberlofa
dependencies:
  - name: postgresql
    version: 1.5.2
    repository: oci://ghcr.io/helmforgedev/helm
    condition: postgresql.enabled
  - name: mysql
    version: 1.4.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
