apiVersion: v2
name: mongodb
description: MongoDB Helm Chart — standalone, replica set, or sharded cluster using the official MongoDB image
type: application
version: 1.3.0
appVersion: "8.2.6"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - mongodb
  - database
  - nosql
  - replicaset
  - sharded
home: https://www.mongodb.com
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/mongo
icon: https://www.mongodb.com/assets/images/global/favicon.ico
