{{- range .Values.configMaps | default list }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" $ }}-{{ .name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- if .binaryData }}
binaryData:
  {{- toYaml .binaryData | nindent 2 }}
{{- end }}
{{- end }}
