{{- if and (include "chart.hasWorkload" .) (ne (.Values.workload.type | default "Deployment") "DaemonSet") .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ include "chart.workloadKind" . }}
    name: {{ include "chart.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  {{- with .Values.hpa.metrics }}
  metrics:
    {{- range . }}
    - type: Resource
      resource:
        name: {{ .resource }}
        target:
          type: {{ .type }}
          {{- if eq .type "AverageValue" }}
          averageValue: {{ .target }}
          {{- else if eq .type "Utilization" }}
          averageUtilization: {{ .target }}
          {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
