domain: https://vaultwarden.example.com

database:
  mode: external
  external:
    existingSecret: vaultwarden-database
    existingSecretUrlKey: database-url

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: vaultwarden.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - vaultwarden.example.com
      secretName: vaultwarden-tls
