domain: https://vaultwarden.example.com

database:
  mode: mysql

mysql:
  enabled: true
  auth:
    database: vaultwarden
    username: vaultwarden
    password: change-me

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: vaultwarden.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - vaultwarden.example.com
      secretName: vaultwarden-tls
