domain: https://vaultwarden.example.com

data:
  persistence:
    enabled: true

smtp:
  enabled: true
  host: smtp.example.com
  port: 587
  from: vaultwarden@example.com
  fromName: Vaultwarden
  security: starttls
  username: vaultwarden
  existingSecret: vaultwarden-smtp
