domain: https://vaultwarden.example.com

smtp:
  enabled: true
  host: smtp.example.com
  port: 587
  from: vaultwarden@example.com
  fromName: Vaultwarden
  security: starttls
  timeout: 15
  username: vaultwarden
  authMechanism: Plain,Login
  heloName: vaultwarden.example.com
  embedImages: true
  existingSecret: vaultwarden-smtp
