apiVersion: v2
name: mysql
description: MySQL for Kubernetes with explicit standalone and replication modes
type: application
version: 1.4.1
appVersion: "8.4"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - mysql
  - database
  - replication
home: https://www.mysql.com/
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/mysql
icon: https://labs.mysql.com/common/themes/sakila/favicon.ico
