{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretPostgresPasswordKey }}: {{ include "postgresql.postgresPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretUserPasswordKey }}: {{ include "postgresql.userPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretReplicationPasswordKey }}: {{ include "postgresql.replicationPassword" . | b64enc | quote }}
{{- end }}
