apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.clientServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    monitoring.mberlofa.io/enabled: "true"
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" (ternary "primary" "standalone" (eq .Values.architecture "replication"))) | nindent 4 }}
{{- if eq .Values.architecture "replication" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.primaryServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    monitoring.mberlofa.io/enabled: "true"
  {{- with .Values.service.primaryAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" "primary") | nindent 4 }}
{{- if gt (int .Values.replication.readReplicas.replicaCount) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.replicasServiceName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    monitoring.mberlofa.io/enabled: "true"
  {{- with .Values.service.replicasAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "postgresql.componentLabels" (dict "root" . "role" "replica") | nindent 4 }}
{{- end }}
{{- end }}
