apiVersion: v2
name: adguard-home
description: AdGuard Home network-wide ad and tracker blocking DNS server with sync and S3 backup
type: application
version: 0.1.0
appVersion: "0.107.73"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - adguard
  - dns
  - ad-blocking
  - tracker-blocking
  - dhcp
  - dns-over-https
  - dns-over-tls
home: https://helmforge.dev/docs/charts/adguard-home
sources:
  - https://github.com/helmforgedev/charts/tree/main/charts/adguard-home
  - https://github.com/AdguardTeam/AdGuardHome
  - https://github.com/bakito/adguardhome-sync
icon: https://adguard.com/img/favicons/apple-touch-icon.png
