mode: production

hostname:
  hostname: https://sso.example.com

database:
  vendor: postgres
  host: postgresql.example.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db
  tls:
    enabled: true
    sslMode: verify-full
    existingConfigMap: keycloak-db-ca
    rootCertFilename: ca.crt

truststore:
  enabled: true
  existingConfigMap: keycloak-extra-cas
  tlsHostnameVerifier: DEFAULT
