mode: production

hostname:
  hostname: https://sso.example.com

database:
  vendor: postgres
  host: postgresql.example.svc
  port: 5432
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

replicaCount: 1
