mode: production

hostname:
  hostname: https://sso.example.com

database:
  external:
    vendor: postgres
    host: postgresql.example.svc
    name: keycloak
    username: keycloak
    existingSecret: keycloak-db

probes:
  profile: heavy-startup
