mode: production

hostname:
  hostname: https://sso.example.com
  admin: https://admin-sso.example.com

database:
  vendor: postgres
  host: postgresql.example.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: sso.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sso.example.com
      secretName: keycloak-tls
