mode: production

hostname:
  hostname: https://sso.example.com

database:
  vendor: postgres
  host: postgresql.example.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
