mode: production

hostname:
  hostname: https://sso.example.com

database:
  vendor: postgres
  host: postgresql.example.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

replicaCount: 3

cache:
  enabled: true
  stack: jdbc-ping

pdb:
  enabled: true
