mode: production

hostname:
  hostname: https://sso.example.com
  admin: https://admin-sso.example.com

database:
  external:
    vendor: postgres
    host: postgresql.example.svc
    name: keycloak
    username: keycloak
    existingSecret: keycloak-db

replicaCount: 3

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

networkPolicy:
  enabled: true

pdb:
  enabled: true
