mode: production

hostname:
  hostname: https://sso.example.com

database:
  vendor: postgres
  host: postgresql.example.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi
priorityClassName: platform-critical
