mode: production

http:
  relativePath: /auth

hostname:
  hostname: https://sso.example.com/auth
  admin: https://admin-sso.example.com/auth

proxy:
  headers: xforwarded

database:
  vendor: postgres
  host: postgresql.example.svc
  name: keycloak
  username: keycloak
  existingSecret: keycloak-db

ingress:
  public:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: sso.example.com
        paths:
          - path: /auth
            pathType: Prefix
  admin:
    enabled: true
    ingressClassName: internal-nginx
    hosts:
      - host: admin-sso.example.com
        paths:
          - path: /auth
            pathType: Prefix
