{{- if not .Values.database.external.existingSecret }}
{{- $password := include "guacamole.dbPassword" . -}}
{{- if $password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-database
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $password | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) .Values.backup.s3.accessKey .Values.backup.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-backup-s3
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.backup.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | b64enc | quote }}
{{- end }}
