# Forge modded server
# helm install minecraft oci://ghcr.io/helmforgedev/helm/minecraft -f modded.yaml

server:
  eula: true
  type: FORGE
  version: "1.20.4"
  motd: "Modded Minecraft Server"
  difficulty: hard
  maxPlayers: 20
  viewDistance: 10
  allowFlight: true

jvm:
  memory: 6G
  useAikarFlags: true

auth:
  onlineMode: true
  ops: "admin_player"

rcon:
  enabled: true

persistence:
  enabled: true
  size: 30Gi

resources:
  requests:
    cpu: "1"
    memory: 6Gi
  limits:
    cpu: "4"
    memory: 10Gi

terminationGracePeriodSeconds: 180
