# Minimal vanilla server
# helm install minecraft oci://ghcr.io/helmforgedev/helm/minecraft -f simple.yaml

server:
  eula: true
  motd: "My Minecraft Server"

jvm:
  memory: 1G

persistence:
  enabled: true
  size: 10Gi
