admin:
  existingSecret: vaultwarden-admin

networkPolicy:
  enabled: true
  ingress:
    allowSameNamespace: false
    additionalFrom:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-system
        podSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
  egress:
    enabled: true
    allowDns: true
    additionalTo:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: database
        podSelector:
          matchLabels:
            app.kubernetes.io/name: postgresql

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
