domain: https://example.com/vaultwarden

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: example.com
      paths:
        - path: /vaultwarden
          pathType: Prefix
  tls:
    - hosts:
        - example.com
      secretName: vaultwarden-tls
