domain: https://vaultwarden.example.com

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: vaultwarden.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - vaultwarden.example.com
      secretName: vaultwarden-tls
