domain: https://vaultwarden.example.com

smtp:
  enabled: true
  host: smtp.example.com
  port: 587
  from: vaultwarden@example.com
  fromName: Vaultwarden
  security: starttls
  timeout: 20
  username: vaultwarden
  authMechanism: Plain,Login
  heloName: vaultwarden.example.com
  embedImages: true
  debug: false
  acceptInvalidCerts: false
  acceptInvalidHostnames: false
  existingSecret: vaultwarden-smtp

data:
  persistence:
    enabled: true
