{{- if and .Values.rcon.enabled (not .Values.rcon.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
data:
  {{- if .Values.rcon.password }}
  rcon-password: {{ .Values.rcon.password | b64enc | quote }}
  {{- else }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "minecraft.fullname" .) }}
  {{- if and $existingSecret (index $existingSecret.data "rcon-password") }}
  rcon-password: {{ index $existingSecret.data "rcon-password" }}
  {{- else }}
  rcon-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) (include "minecraft.backupEnabled" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft.fullname" . }}-backup
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  access-key: {{ .Values.backup.s3.accessKey | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
