apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: minecraft
      port: {{ .Values.service.port }}
      targetPort: minecraft
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.rcon.enabled }}
    - name: rcon
      port: {{ .Values.rcon.port }}
      targetPort: rcon
      protocol: TCP
    {{- end }}
    {{- if .Values.geyser.enabled }}
    - name: bedrock
      port: {{ .Values.geyser.port }}
      targetPort: bedrock
      protocol: UDP
    {{- end }}
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- if and .Values.rcon.enabled .Values.rcon.serviceEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}-rcon
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
    app.kubernetes.io/component: rcon
spec:
  type: {{ .Values.rcon.serviceType }}
  ports:
    - name: rcon
      port: {{ .Values.rcon.port }}
      targetPort: rcon
      protocol: TCP
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}
