# CI: backup enabled
postgresql:
  auth:
    password: ci-test-password

backup:
  enabled: true
  schedule: "0 3 * * *"
  s3:
    endpoint: https://s3.amazonaws.com
    bucket: guacamole-backup
    prefix: guacamole
    accessKey: AKIA123456
    secretKey: secret123456
