# CI scenario: pre-configured AdGuard Home (skips setup wizard)
config:
  adGuardHome:
    http:
      pprof:
        port: 6060
        enabled: false
      address: 0.0.0.0:80
      session_ttl: 720h
    users:
      - name: admin
        password: "$2y$10$hW1sBKsFxvB8gKIYQl1w4O/4LHDoqq1mA92Dg6rNULYAx4YPamq0K"
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      upstream_dns:
        - https://dns.cloudflare.com/dns-query
        - https://dns.google/dns-query
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
      protection_enabled: true
      filtering_enabled: true
    filtering:
      protection_enabled: true
      filtering_enabled: true
    filters:
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
        name: AdGuard DNS filter
        id: 1
    schema_version: 29

service:
  dns:
    type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: adguard.example.com
      paths:
        - path: /
          pathType: Prefix
