architecture: replication

auth:
  existingSecret: mysql-auth

tls:
  enabled: true
  existingSecret: mysql-tls
  requireSecureTransport: true
  client:
    enabled: true

metrics:
  enabled: true

networkPolicy:
  enabled: true
  metrics:
    enabled: true

replication:
  source:
    persistence:
      enabled: false
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: false
