apiVersion: v2
name: redis
description: Redis Helm Chart for standalone, replication, sentinel, and cluster topologies
type: application
version: 1.2.0
appVersion: "8.6.0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - redis
  - cache
  - datastore
  - sentinel
  - cluster
home: https://redis.io
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/redis
icon: https://redis.io/favicon.ico
