apiVersion: v2
name: guacamole
description: Apache Guacamole clientless remote desktop gateway with guacd, PostgreSQL or MySQL, OIDC/SAML SSO, and S3 backup
type: application
version: 1.0.0
appVersion: "1.6.0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - guacamole
  - remote-desktop
  - rdp
  - vnc
  - ssh
  - gateway
  - oidc
  - saml
home: https://guacamole.apache.org
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/apache/guacamole-server
  - https://github.com/apache/guacamole-client
icon: https://guacamole.apache.org/images/logos/guac-logo.svg
dependencies:
  - name: postgresql
    version: 1.5.2
    repository: oci://ghcr.io/helmforgedev/helm
    condition: postgresql.enabled
  - name: mysql
    version: 1.4.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
