{{- if .Values.php.ini }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.configMapName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  custom.ini: |
    {{- .Values.php.ini | nindent 4 }}
{{- end }}
