apiVersion: v2
name: rabbitmq
description: RabbitMQ for Kubernetes with explicit single-node and cluster modes
type: application
version: 1.1.0
appVersion: "4.2.4"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - rabbitmq
  - amqp
  - messaging
  - queue
  - cluster
home: https://www.rabbitmq.com/
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/docker-library/rabbitmq
icon: https://www.rabbitmq.com/img/favicon.png
